# MySQL Database
MYSQL_USER="tribui"
MYSQL_PASS="Tri2107"
MYSQL_HOST="localhost"
MYSQL_DB="SmartRoomManager"

# Arduino Serial Client
ARDUINO_SERIAL_PORT="/dev/ttyACM0"
ARDUINO_SERIAL_BAUD=9600
ARDUINO_PING_INTERVAL_S = 1.0
ARDUINO_SERIAL_TIMEOUT_S = 0.2
ARDUINO_ALIVE_TIMEOUT_S = 3.0